# -*- coding: utf-8 -*-
"""Assessment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FkAMRwTFRUzBdrWq9V18TKCRJMg9nSHw
"""

import pandas as pd
import seaborn as sns

import statsmodels.api as sm

df = pd.read_excel("/content/Data set.xlsx")
df

import statsmodels.formula.api as smf

model = smf.ols(formula = "Sales ~ CPI + discounts + offers", data = df)

res = model.fit()

print (res.summary())

new_data_points = pd.DataFrame({'CPI': [5000, 4000], 'discounts': [3, 8], 'offers': [20, 19]})
new_data_points

predictions = res.predict(new_data_points)

predictions

